config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users

  resources :chat_rooms



  root 'chat_rooms#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  validates :body, presence: true, length: {minimum: 2, maximum: 1000}

  after_create_commit { MessageBroadcastJob.perform_later(self) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  def name
    email.split('@')[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :authenticate_user!, :except => [:index]
  def index
    @chat_rooms = ChatRoom.all.order(updated_at: :desc)
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room created'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  def edit
    @chat_room = ChatRoom.find_by(id: params[:id])
  end

  def update
    @chat_room = current_user.chat_rooms.find_by(id: params[:id])
    @chat_room.update(chat_room_params)
    if @chat_room.update(chat_room_params)
      flash[:success] = 'Chat room updated'
      redirect_to @chat_room
    else
      render 'edit'
    end
  end

  def destroy
    @chat_room = ChatRoom.find_by(id: params[:id])
    @chat_room.destroy
    if @chat_room.save
      flash[:success] = 'Chat room deleted'
    end
    redirect_to chat_rooms_path
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title, :description, :ephemeral)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end

  def format_datetime_to_local(datetime)
    datetime.in_time_zone('Asia/Manila').strftime("%b %e, %Y %I:%M %p")
  end

  def katpadi?
    current_user.email == 'katpadillaaa@gmail.com'
  end
end

app/views/chat_rooms/_chat_room.html.erb
<div class="card card-block">
    <h4 class="card-title"><%= link_to "#{chat_room.title}", chat_room_path(chat_room) %></h4>
    <p class="card-text"><%= chat_room.description %></p>
    <p class="card-text">
    <small class="text-muted">Created by
    <%= link_to "#{chat_room.user.name}", '#' %> on
    <%= format_datetime_to_local(chat_room.created_at) %></small></p>
</div>

app/views/chat_rooms/edit.html.erb
<h1>Edit chat room</h1>

<%= form_for @chat_room do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>

    </div>

    <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, autofocus: true, class: 'form-control' %>
</div>

  <%= f.submit "Save", class: 'btn btn-primary' %>
<% end %>

app/views/chat_rooms/index.html.erb
<section class="jumbotron text-xs-center">
      <div class="container">
        <h1 class="jumbotron-heading">Quickieee!</h1>
        <p class="lead text-muted">This is a simple web chat. Create new chat rooms in seconds. Need a quickie? Get a room!</p>
        <p>
           <%= link_to 'Create New Room', new_chat_room_path, class: 'btn btn-primary' %>
        </p>
      </div>
    </section>
  <div class="card-columns">
    <%= render @chat_rooms %>
    </div>

app/views/chat_rooms/new.html.erb
<h1>Create a new room</h1>

<%= form_for @chat_room do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>

    </div>

    <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, autofocus: true, class: 'form-control' %>
</div>

  <%= f.submit "Create", class: 'btn btn-primary' %>
<% end %>

app/views/chat_rooms/show.html.erb
<div class=" text-center">
    <div class="box">
        <% if (current_user == @chat_room.user) || katpadi?  %>
          <div class="pull-right">
            <%= link_to chat_room_path(@chat_room), method: :delete do %>
              <i class="fa fa-trash-o"></i>
            <% end %>

            <%= link_to edit_chat_room_path(@chat_room) do %>
              <i class="fa fa-pencil"></i>
            <% end %>
          </div>
        <% end %>
        <div class="box-content">
            <h3 class="tag-title"><%= @chat_room.title %> </h3>
            <p><%= @chat_room.description %></p>
        </div>
        <div>
          <div class="message-wrap">
          <div id="messages" data-chat-room-id="<%= @chat_room.id %>">
            <%= render @chat_room.messages %>
          </div>
          </div>
          <%= form_for @message, url: '#' do |f| %>
            <%= hidden_field_tag 'chat_room_id', @chat_room.id %>
            <br>
            <div class="form-group">
              <%= f.text_area :body, placeholder: 'Write a comment...', class: 'form-control' %>
            </div>
          <% end %>
        </div>

    </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
<div class="row">
  <div class="alert alert-info alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= content_tag :div, value, class: "flash #{key}" %>
  </div>
</div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-light bg-faded">
  <button class="navbar-toggler hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"></button>
  <div class="collapse navbar-toggleable-md" id="navbarResponsive">
    <a class="navbar-brand" href="#"><i class="fa fa-commenting"></i> Quickeee!</a>

    <ul class="nav navbar-nav">
      <li class="nav-item">
        <%= link_to "Chat Rooms", chat_rooms_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="responsiveNavbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">katpadi</a>
        <div class="dropdown-menu" aria-labelledby="responsiveNavbarDropdown">
          <a class="dropdown-item" href="https://twitter.com/katpadi"><i class="fa fa-twitter"></i> katpadi</a>
          <a class="dropdown-item" href="https://github.com/katpadi/quickeee"><i class="fa fa-github"></i> github</a>
          <a class="dropdown-item" href="hello@katpadi.ph"><i class="fa fa-envelope"></i> email</a>
        </div>
      </li>
    </ul>
    <div class=" float-lg-right">
      <% if current_user %>
      <small>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      </small>
      <% else %>
      <small><%= link_to "Sign In", new_user_session_path %></small>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quickeee!</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <%= render 'layouts/nav' %>
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>

    <footer class="text-muted">
      <div class="container">
        <p class="float-xs-right">
          <a href="#">Back to top</a>
        </p>
<pre>Quickeee! © is a troll web chat app
created by @katpadi to try out Rails 5's Action Cable feature.
Please do not take me, or this, seriously.
</pre>
      </div>

    </footer>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="media msg">
  <div class="col-md-1">
    <%= gravatar_for message.user %>
  </div>
  <div class="col-md-11">
    <div class="row">
    <p class="col-md-8 name"><%= message.user.name %></p>
    <p class="col-md-4"><small class=" time"><i class="fa fa-clock-o"></i> <%= format_datetime_to_local(message.created_at) %></small></p>
    </div>
    <%= message.body %>

  </div>
</div>